In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#import seaborn as sns
import re
%matplotlib inline


# import dataset

Can someone please change the csv path to github, I don't know how to do that

In [21]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [27]:
test.head()

message  tweetid
0  Europe will now be looking to China to make su...   169760
1  Combine this with the polling of staffers re c...    35326
2  The scary, unimpeachable evidence that climate...   224985
3  @Karoli @morgfair @OsborneInk @dailykos \nPuti...   476263
4  RT @FakeWillMoore: 'Female orgasms cause globa...   872928

In [23]:
train['sentiment'].unique()


array([ 1,  2,  0, -1], dtype=int64)

In [24]:
train['tweetid'].nunique()

15819

In [25]:
len(train)

15819

In [26]:
df =train.drop(['tweetid'],axis = 1)

In [28]:
df['message'][0]

"PolySciMajor EPA chief doesn't think carbon dioxide is main cause of global warming and.. wait, what!? https://t.co/yeLvcEFXkC via @mashable"

In [29]:
df.isnull().sum()

sentiment    0
message      0
dtype: int64

In [30]:
df['sentiment'].value_counts()

 1    8530
 2    3640
 0    2353
-1    1296
Name: sentiment, dtype: int64

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X = df['message']
y = df['sentiment']

In [33]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [34]:
# count vectorization which builds a dictionary of features
from sklearn.feature_extraction.text import CountVectorizer

In [35]:
count_vect = CountVectorizer()

In [36]:
X[0]

"PolySciMajor EPA chief doesn't think carbon dioxide is main cause of global warming and.. wait, what!? https://t.co/yeLvcEFXkC via @mashable"

In [37]:
X_train_counts = count_vect.fit_transform(X_train)

In [38]:
X_train_counts.shape

(10598, 23895)

In [39]:
from sklearn.feature_extraction.text import TfidfTransformer

In [40]:
tfidf_transformer = TfidfTransformer()

In [41]:
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

In [42]:
X_train_tfidf.shape

(10598, 23895)

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)

In [44]:
from sklearn.svm import LinearSVC
clf = LinearSVC()
clf.fit(X_train_tfidf,y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [45]:
from sklearn.pipeline import Pipeline
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('clf',LinearSVC())])
text_clf.fit(X_train,y_train)

Pipeline(memory=None,
     steps=[('tfidf', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,...ax_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0))])

In [49]:
predictions = text_clf.predict(test['message'])

In [50]:
predictions

array([1, 1, 1, ..., 2, 0, 1], dtype=int64)

In [52]:
results = pd.DataFrame()

In [53]:
results['tweetid'] = test['tweetid']
results['sentiment'] = predictions
results.reset_index(drop=True,inplace=True)

In [54]:
results.head()

tweetid  sentiment
0   169760          1
1    35326          1
2   224985          1
3   476263          1
4   872928          0

In [57]:
results.to_csv(r"results1.csv",sep=',',index=False)
len(results)


10546

# Note these metrics are based on X_test

In [34]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,predictions))

[[ 198   50  157   23]
 [  28  319  319   71]
 [  38  125 2439  259]
 [   4   23  214  954]]


In [35]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

          -1       0.74      0.46      0.57       428
           0       0.62      0.43      0.51       737
           1       0.78      0.85      0.81      2861
           2       0.73      0.80      0.76      1195

   micro avg       0.75      0.75      0.75      5221
   macro avg       0.72      0.64      0.66      5221
weighted avg       0.74      0.75      0.74      5221



In [36]:
from sklearn import metrics
metrics.accuracy_score(y_test,predictions)

0.748898678414097

In [44]:
train[(train['sentiment'] == -1)]

sentiment                                            message  tweetid
28            -1  Sally Kohn’s latest evidence of climate change...   355491
46            -1  @realDonaldTrump Carbon Tax is a Globalist ide...    61141
48            -1  RT @SteveSGoddard: We had winds close to 100 M...   719523
56            -1  @MissLizzyNJ lmao 😂 snowflakes ❄️ complaining ...   911385
57            -1  RT @Dawn2334Dawn: This is ONE of Arnold Schwar...   768263
107           -1  RT @Fruitloopian: Why is there snow in March i...   798585
113           -1  can someone pls explain to me why it's -37 in ...   337974
116           -1  Explain that my global warming advocates. http...   472265
121           -1  @TomiLahren kinda funny the professors talk sh...   740194
129           -1  RT @signordal: New global warming study is ter...   473664
147           -1  @CBSNews You're not going to get away with thi...   621536
149           -1  RT @CharlieDaniels: I'm not worried about glob...   565424
164           -1  global warming is a hoax perpetrated by the ch...     4935
176           -1  RT @Carbongate: Physicist - CO2 does not cause...   809373
181           -1  Agreed! Man-made climate change is a man-made ...   245892
185           -1  RT @tamorley: @ZekeJMiller But why a carbon ta...   453052
195           -1  RT @Mike_Beacham: Fed scientist cooked climate...   687404
202           -1  RT @CounterMoonbat: The people who predicted p...   479445
227           -1            @zrastall17 climate change is #fakenews     3014
229           -1  RT @MR_BREXIT: Good news that @realDonaldTrump...   242418
252           -1  I was thinking the same thing. Same goes with ...   301923
258           -1  RT @Uniocracy: They'll tell you theyre doing i...   529327
262           -1  RT @newsfakenews: TODD STARNES: Hey NPR — Take...   120315
264           -1  @NobamaDotCom @LibbyRafferty @BIZPACReview Fun...    49204
269           -1  RT @CounterMoonbat: The people who predicted p...   376353
277           -1  RT @realDonaldTrump: The concept of global war...   950779
279           -1  Natural climate change wins man-made climate c...   716256
283           -1  RT @HarmlessYardDog: 21 kids aged 9 to 20 are ...   684619
320           -1  Selling global warming as scientific vs govern...   126568
323           -1  @sallykohn They're related when part of a larg...   802130
...          ...                                                ...      ...
15361         -1  RT @realDonaldTrump: It's freezing outside, wh...   243511
15362         -1  RT @peddoc63: This is what 'environmentalists'...   631021
15374         -1  RT @RealJamesWoods: Federal scientist cooked c...   754803
15399         -1  The real problem is not global warming but glo...   513561
15417         -1  RT @FoundinNV: John Kerry lands in Antarctica,...   493648
15421         -1  @ninaspringle @JimHarris @ChristineMilne \n\nB...   508898
15431         -1  The @Guardian's 4th mention of 'global warming...   578200
15438         -1  I see an unholy alliance between PP and climat...   852787
15442         -1  @murrayjohnsonjr @AstroKatie @KetanJ0 u must n...   926229
15460         -1  Science-fiction personality preaches a fearful...   726028
15474         -1  RT @USFreedomArmy: Can anyone say 'Man-made gl...     1422
15509         -1  Liberals changed the term 'global warming' to ...   841847
15510         -1  @greenpeaceusa hey dumbfucks climate change is...   205844
15520         -1  RT @hrkbenowen: Tucker Carlson obliterates lef...   329497
15568         -1  RT @realDonaldTrump: It's freezing outside, wh...   230157
15608         -1  RT @wrmead: By focusing on climate change, the...   548220
15618         -1   @DanaHoule But climate change is a Chinese hoax.   625660
15633         -1  @DineshDSouza @cenkuygur I like how it went fr...   912594
15644         -1  RT @murfrw2016: Gore is scamming more money fr...   497630
15647         -1  Mansbridge implies link between big storm in A...   230309
156

Testing the sentiment analysis on own personal string

In [52]:
text_clf.predict(['Stop tweeting about things that do not exist #climatechange'])

array([1], dtype=int64)

# trying the logistic regression model

In [4]:
# Remove urls
pattern_url = r'http[s]?://(?:[A-Za-z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9A-Fa-f][0-9A-Fa-f]))+'
subs_url = r'url-web'
df['message'] = df['message'].replace(to_replace = pattern_url, value = subs_url, regex = True)

In [5]:
# Make lower case
df['message'] = df['message'].str.lower()

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
# Let's use the count vectorizer with its default hyperparameters
vect = CountVectorizer()
X_count = vect.fit_transform(df['message'])

In [8]:
X = X_count.toarray()

In [64]:
from sklearn.linear_model import LogisticRegression

In [65]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=27)

In [66]:
# Here 'ovr' indicates that we have selected our One-vs-Rest strategy. 
logreg = LogisticRegression(multi_class='ovr')

In [67]:
logreg.fit(X_train, y_train)

C:\Users\admin\anaconda3\envs\nlp_course\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [68]:
# Generate predictions
y_pred_test = logreg.predict(X_test)

In [69]:
y_pred_test

array([ 2,  2,  2, ...,  1,  1, -1], dtype=int64)

In [71]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred_test))

[[ 115   33   81   17]
 [  23  202  186   44]
 [  30   88 1468  144]
 [   3   19  123  588]]


In [73]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

          -1       0.67      0.47      0.55       246
           0       0.59      0.44      0.51       455
           1       0.79      0.85      0.82      1730
           2       0.74      0.80      0.77       733

   micro avg       0.75      0.75      0.75      3164
   macro avg       0.70      0.64      0.66      3164
weighted avg       0.74      0.75      0.74      3164



In [9]:
type_labels = ['1','2','0','-1']